// Code generated by "stringer -type=Type"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[EOF-1]
	_ = x[COMMENT-2]
	_ = x[MULTILINE_COMMENT-3]
	_ = x[DIRECTIVE-4]
	_ = x[IDENT-5]
	_ = x[INT-6]
	_ = x[HEX-7]
	_ = x[FLOAT-8]
	_ = x[RUNE-9]
	_ = x[STRING-10]
	_ = x[ADD-11]
	_ = x[SUB-12]
	_ = x[MUL-13]
	_ = x[DIV-14]
	_ = x[MOD-15]
	_ = x[AND-16]
	_ = x[BOR-17]
	_ = x[XOR-18]
	_ = x[LSH-19]
	_ = x[RSH-20]
	_ = x[BNT-21]
	_ = x[QUESTION-22]
	_ = x[ADD_ASSIGN-23]
	_ = x[SUB_ASSIGN-24]
	_ = x[MUL_ASSIGN-25]
	_ = x[DIV_ASSIGN-26]
	_ = x[XOR_ASSIGN-27]
	_ = x[BOR_ASSIGN-28]
	_ = x[MOD_ASSIGN-29]
	_ = x[LAND-30]
	_ = x[LOR-31]
	_ = x[INC-32]
	_ = x[DEC-33]
	_ = x[EQL-34]
	_ = x[SEQ-35]
	_ = x[NEQ-36]
	_ = x[SNE-37]
	_ = x[LSS-38]
	_ = x[GTR-39]
	_ = x[ASSIGN-40]
	_ = x[NOT-41]
	_ = x[LEQ-42]
	_ = x[GEQ-43]
	_ = x[LPAREN-44]
	_ = x[LBRACK-45]
	_ = x[LBRACE-46]
	_ = x[COMMA-47]
	_ = x[PERIOD-48]
	_ = x[RPAREN-49]
	_ = x[RBRACK-50]
	_ = x[RBRACE-51]
	_ = x[SEMICOLON-52]
	_ = x[COLON-53]
	_ = x[DECL-54]
	_ = x[LAMBDA-55]
	_ = x[BREAK-56]
	_ = x[CONTINUE-57]
	_ = x[IF-58]
	_ = x[ELSE-59]
	_ = x[FOR-60]
	_ = x[WHILE-61]
	_ = x[RETURN-62]
	_ = x[IMPORT-63]
	_ = x[SWITCH-64]
	_ = x[CASE-65]
	_ = x[DEFAULT-66]
	_ = x[LET-67]
	_ = x[VAR-68]
	_ = x[CONST-69]
	_ = x[FUNCTION-70]
	_ = x[ENUM-71]
	_ = x[NULL-72]
	_ = x[UNDEFINED-73]
	_ = x[INTERFACE-74]
	_ = x[EXPORT-75]
	_ = x[NEW-76]
	_ = x[CLASS-77]
	_ = x[TRUE-78]
	_ = x[FALSE-79]
	_ = x[TRY-80]
	_ = x[CATCH-81]
	_ = x[FINALLY-82]
	_ = x[THROW-83]
}

const _Type_name = "ERROREOFCOMMENTMULTILINE_COMMENTDIRECTIVEIDENTINTHEXFLOATRUNESTRINGADDSUBMULDIVMODANDBORXORLSHRSHBNTQUESTIONADD_ASSIGNSUB_ASSIGNMUL_ASSIGNDIV_ASSIGNXOR_ASSIGNBOR_ASSIGNMOD_ASSIGNLANDLORINCDECEQLSEQNEQSNELSSGTRASSIGNNOTLEQGEQLPARENLBRACKLBRACECOMMAPERIODRPARENRBRACKRBRACESEMICOLONCOLONDECLLAMBDABREAKCONTINUEIFELSEFORWHILERETURNIMPORTSWITCHCASEDEFAULTLETVARCONSTFUNCTIONENUMNULLUNDEFINEDINTERFACEEXPORTNEWCLASSTRUEFALSETRYCATCHFINALLYTHROW"

var _Type_index = [...]uint16{0, 5, 8, 15, 32, 41, 46, 49, 52, 57, 61, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100, 108, 118, 128, 138, 148, 158, 168, 178, 182, 185, 188, 191, 194, 197, 200, 203, 206, 209, 215, 218, 221, 224, 230, 236, 242, 247, 253, 259, 265, 271, 280, 285, 289, 295, 300, 308, 310, 314, 317, 322, 328, 334, 340, 344, 351, 354, 357, 362, 370, 374, 378, 387, 396, 402, 405, 410, 414, 419, 422, 427, 434, 439}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
